version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-itau
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: investimentos
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
